# Generated by Django 4.2.16 on 2025-09-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_merge_20250908_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admissao',
            unique_together={('codigo', 'data_admissao')},
        ),
        migrations.AlterUniqueTogether(
            name='desligamento',
            unique_together={('codigo', 'demissao')},
        ),
        migrations.AlterUniqueTogether(
            name='distrato',
            unique_together={('cpf', 'data_demissao')},
        ),
    ]
